### PR TITLE
[MNT] add tests restructure repo

### LINKED ISSUE #37: Add tests (restructure repo)
Tests should be in the root dir of the repo.
In general some restructuring might be necessary ;)

### PR DESCRIPTION
**Pull request by barbarastrasser**
- Closes #37 

Changes proposed in this pull request:

- rearranged folder structure
- added docker docs and parsing documentation (from hackmd) to readme

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [ ] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

**Comment by barbarastrasser** [comment]
@tvilight4 - I guess I was a bit inattentive when reviewing the last PR, but now I was looking explicitly at the tests and realized that in the [test file of the categorization](https://github.com/neurobagel/annotation-tool-ai/blob/37-add-tests-restructure-repo/tests/test_llm_categorization.py) the actual code is in there instead of the test functions. Maybe a copy-paste mishap. Maybe you could add the tests in this PR so that everything is correctly arranged?

**Comment by barbarastrasser** [comment]
@rmanaem Could you please have a look at the repo structure as it is now so that I still fix things if they are off within this PR?

**Comment by tvilight4** [comment]
> @tvilight4 - I guess I was a bit inattentive when reviewing the last PR, but now I was looking explicitly at the tests and realized that in the [test file of the categorization](https://github.com/neurobagel/annotation-tool-ai/blob/37-add-tests-restructure-repo/tests/test_llm_categorization.py) the actual code is in there instead of the test functions. Maybe a copy-paste mishap. Maybe you could add the tests in this PR so that everything is correctly arranged?

Hi sorry for that will update that asap!

**Review by rmanaem — APPROVED** [review]
Thanks for making the changes @barbarastrasser, the structure looks good 🧑‍🍳

**Review by tvilight4 — APPROVED** [review]
The required changes and updates have been made So I think its good to go now :cook: !!

**Pull request merged**
